# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-efax}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Szymon Nowak"]
  s.date = %q{2009-09-21}
  s.email = %q{szimek@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/efax.rb",
     "ruby-efax.gemspec",
     "test/efax_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/szimek/ruby-efax}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ruby-efax}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby library for accessing the eFax Developer service}
  s.test_files = [
    "test/efax_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
